import type { Metadata } from "next";
import { Inter } from "next/font/google";
import DashboardProvider from "./dashboard/DashboardProvider";
import "./globals.css";
import Header from "./header/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <DashboardProvider>{children}</DashboardProvider>
      </body>
    </html>
  );
}
